### ISSUE TITLE
Missing README and LICENSE

### ISSUE THREAD

**Issue by Flamacue** [aepks/aepks.com#3]
This repository should probably include a README of its description/instructions, and a software license ;P

**Comment by Flamacue** [comment]
by this I mean a repository specific README and LICENSE, not what's included in the static folder

**Comment by DanielFallon** [comment]
I fix tomorrow. I am pooped

**Comment by DanielFallon** [comment]
I fixed

***I drunk***

I fixed

YEEEEEEEEEEt
